version: '3.8'
services:
  mysql:
    container_name: mysql
    platform: ${DOCKER_PLATFORM}
    image: mysql:5.7
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'

networks:
  default:
    driver: bridge
