shared:
  redis:
    host: redis
    port: 6379
    password: q/w.e,rm

# Apps
www:
  host:
  port:
  db:
    type: mysql
    host: localhost
    port: 3306
    username: root
    password: root
    database: test
